/**
* LOGIN ROUTES. 
* Query for a specific user.
* If no user document's is stored in MongoDb than the user is saved with an insert.
* If user is present and inactive, status is set to active (active = 1).
* If user is present on db and is active then a new nickname plus an avatar is generated by 
* the system (with a random number suffix); the reference is send to the client side. 
*/
module.exports = function(model) {
    return function (req, res) {
        if (req.query.nickname) {

            var queryUser = model.user.find({
                nickname : req.query.nickname
            });

            queryUser.exec(function (error, user) {
                if (error) throw error;

                if (user.length > 0) {
                    if (user[0].active === 1) {
                        var user = new model.user({
                            nickname : req.query.nickname + '-' + Math.floor(Math.random() * 1000 + 1),
                            avatar   : '/get-avatar/' + req.query.nickname + '-' + Math.floor(Math.random() * 1000 + 1),
                            active   : 1,
                            messages : []
                        });

                        user.save(function (error) {
                            if (error) throw error;

                            res.send(user);
                        });

                    } else {
                        var updateUser = model.user.findOneAndUpdate({
                            nickname : req.query.nickname
                        }, {active : 1});

                        updateUser.exec(function(error, updated) {
                            res.send(updated);
                        });
                    }
                } else {
                    var user = new model.user({
                        nickname : req.query.nickname,
                        avatar   : '/get-avatar/' + req.query.nickname,
                        active   : 1,
                        messages : []
                    });

                    user.save(function (error) {
                        if (error) throw error;

                        res.send(user);
                    });
                }
                                   
            });
        } 
    };
};